argo-cd:
  #  installCRDs: false
  global:
    image: 
      repository: cyrilix/argocd
      tag: v2.1.6
  dex:
    enabled: false
  server:
    ingress:
      enabled: true
      paths: 
        - /argocd
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
